version: '3.8'

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: otica
            MARIADB_USER: root
            MARIADB_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
